### ISSUE TITLE
Fails on multiple cursors

### ISSUE THREAD

**Issue by mattandrews** [nkmk/atom-remove-whitespace#1]
If I have multiple lines selected at once and want to remove whitespace, it duplicates the last selected text to all changes, eg:

![bug](https://cloud.githubusercontent.com/assets/394376/15424209/4d418300-1e79-11e6-8022-a7f229512e85.gif)

**Comment by nkmk** [comment]
Thank you for reporting the issue!

I released v0.2.1 that supports multiple selections. I hope it works as you expect.

**Comment by mattandrews** [comment]
Thank you! All fixed:

![fixed](https://cloud.githubusercontent.com/assets/394376/15447536/73e800be-1f3d-11e6-9151-d2db38b2b2d4.gif)
